# Setup
title:               Toronto AI in Robotics Seminar
tagline:             University of Toronto 
description:         'AI in Robotics Reading Group University of Toronto`'
url:                 https://robotics.cs.toronto.edu/
baseurl:             /toronto-air
permalink:           pretty

# paginate:            5

# About/contact
author:
  name:              Animesh Garg
  url:               ''
  email:             garg@cs.toronto.edu

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
