# Setup
title:               Robotics-RG
tagline:             University of Toronto AI in Robotics Reading Group
description:         'AI in Robotics Reading Group University of Toronto`'
url:                 https://www.pair.toronto.edu
baseurl:             /robotics-rg
permalink:           pretty

# paginate:            5

# About/contact
author:
  name:              Animesh Garg
  url:               ''
  email:             garg@cs.toronto.edu

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
